"""teacher_course_class_sanity_id

Revision ID: c73348c4bbe7
Revises: 3dd22736f22a
Create Date: 2026-03-10 17:52:29.311248

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c73348c4bbe7'
down_revision: Union[str, None] = '3dd22736f22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_constraint('teacher_course_classes_class_id_fkey', 'teacher_course_classes', type_='foreignkey')
    op.alter_column('teacher_course_classes', 'class_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False,
               postgresql_using='class_id::text')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('teacher_course_classes_class_id_fkey', 'teacher_course_classes', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    op.alter_column('teacher_course_classes', 'class_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
